app_server_ip = "10.10.10.20"
db_server_ip = "10.10.10.10"

Vagrant.configure("2") do |config|

  config.vm.provider :virtualbox do |v|
    v.memory = 512
  end

  config.vm.define "dbserver" do |db|
    db.vm.box = "ubuntu/xenial64"
    db.vm.hostname = "dbserver"
    db.vm.network :private_network, ip: dbserver_ip

    db.vm.provision "ansible" do |ansible|
      ansible.playbook = "playbooks/site.yml"
      ansible.groups = {
      "db" => ["dbserver"],
      "db:vars" => {"mongo_bind_ip" => "0.0.0.0"}
      }
    end
  end

  config.vm.define "appserver" do |app|
    app.vm.box = "ubuntu/xenial64"
    app.vm.hostname = "appserver"
    app.vm.network :private_network, ip: app_server_ip

    app.vm.provision "ansible" do |ansible|
      ansible.playbook = "playbooks/site.yml"
      ansible.groups = {
      "app" => ["appserver"],
      "app:vars" => { "db_host" => db_server_ip}
      }
      ansible.extra_vars = {
        "deploy_user" => "ubuntu",
        "nginx_sites" => {
          "default" => [
            "listen 80",
            "server_name 'reddit'",
            "location / { proxy_pass http://#{app_server_ip}:9292; }"
          ]
        }
      }
    end
  end
end
