---
dependency:
  name: galaxy
driver:
  name: vagrant
  provider:
    name: virtualbox
lint:
  name: yamllint
platforms:
  - name: instance
    box: ubuntu/xenial64
    memory: 512
    cpus: 1
provisioner:
  name: ansible
lint: ansible-lint
verifier:
  name: testinfra
  additional_files_or_dirs:
    - ./tests
